Add evm login functionality
dappforce/grillchat pull request #179
Opened 2023-06-05 06:03 UTC by samchuk-vlad

2023-06-05 14:58 UTC, teodorus-nathaniel requested changes

2023-06-05 14:58 UTC, teodorus-nathaniel commented on src/stores/my-account.ts
> +
remove this extra space

2023-06-05 14:58 UTC, teodorus-nathaniel commented on src/components/CommonModalContent.tsx
I'm not sure with this put in here, but I understand the reasoning, because you need this in 2 different folders right?
so now I think maybe you should move out the `ProfileModal`, with `ProfileAvatar`, into a same folder with `LoginModal`

maybe `auth` folder?
so
```
auth/
  LoginModal/
    ...
  ProfileModal/
    ...
  CustomConnectButton.tsx
  CommonModalContent.tsx
```

for other files, like `ProfilePreview` or `ProfileAvatar`, I leave it to what you think 😄, I'm also not sure about them haha

what do you think about this change I proposed?

2023-06-05 23:49 UTC, samchuk-vlad commented on src/components/CommonModalContent.tsx
It's make sense

2023-06-08 14:44 UTC, olehmell approved these changes

2023-06-08 14:45 UTC, merged