Add donate feature
dappforce/grillchat pull request #213
Opened 2023-06-20 13:42 UTC by samchuk-vlad

2023-06-21 14:03 UTC, teodorus-nathaniel requested changes

2023-06-21 14:03 UTC, teodorus-nathaniel commented on src/pages/api/prices.ts
> +export type ApiAccountsDataParams = z.infer<typeof querySchema>
Rename type

2023-06-22 07:46 UTC, samchuk-vlad commented on src/components/ProfilePreview.tsx
> +                textClassName='font-mono leading-none text-[15px] leading-[14px]'
Yes I really need 15px

2023-06-26 13:44 UTC, teodorus-nathaniel approved these changes

2023-06-26 13:53 UTC, merged