Add sub donation to donation modal
dappforce/grillchat pull request #508
Opened 2023-12-27 11:51 UTC by samchuk-vlad

2023-12-27 12:29 UTC, olehmell requested changes

2023-12-27 12:29 UTC, olehmell commented on src/components/auth/ProfileModal/contents/AccountContent.tsx
> +  // e9eff4
What is?

2023-12-27 12:29 UTC, olehmell commented on src/components/extensions/donate/DonateModal/donateForm/TokenItemPreview.tsx
> +      ? new BigNumber(price).multipliedBy(balanceValue).toFixed(4)
Make sense do some wrapper for the calculation function, you use it in few places

2023-12-27 12:29 UTC, olehmell commented on src/components/extensions/donate/DonateModal/donateForm/index.tsx
> +  })
Why we are building both?

You can dot something like:

```
isEvmChain = chainKind === 'evm'
```

And use it in all places

2023-12-27 12:29 UTC, olehmell commented on src/components/extensions/donate/hooks/useBuildBeforeMessegeSend.tsx
> +import { useGetChainDataByNetwork } from '@/services/chainsInfo/query'
typo in file name Message

So maybe cal it like useBuildDontationMessage ?

Because BeforeMessageSend is unclear for reading

2023-12-27 12:32 UTC, olehmell approved these changes

2023-12-27 12:32 UTC, merged

2023-12-27 13:03 UTC, teodorus-nathaniel commented on src/subsocial-query/subsocial/lazyMutation.ts
> +export function useLazySubstrateMutation<Data, Context = undefined>(
is the difference only related to the api?
so in here, you provide the api endpoint and it creates the api instance lazily?

2023-12-27 13:03 UTC, teodorus-nathaniel commented on tsconfig.json
> +    "src/services/subsocial/chainsInfo/query.tx"
what is this?

2024-01-05 07:47 UTC, samchuk-vlad commented on src/subsocial-query/subsocial/lazyMutation.ts
> +export function useLazySubstrateMutation<Data, Context = undefined>(
Yes, the difference with usual mutation is that I use endpoint from props to connect to the node